# Generated by Django 5.1.6 on 2025-05-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='系列标题')),
                ('description', models.TextField(verbose_name='系列描述')),
                ('cover_image', models.ImageField(upload_to='series_covers/', verbose_name='系列封面图')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='视频标题')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='视频文件')),
                ('episode_number', models.IntegerField(verbose_name='集数')),
                ('description', models.TextField(verbose_name='视频描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.series')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
