# Generated by Django 5.1.6 on 2025-05-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
    ]
