# Generated by Django 5.1.6 on 2025-05-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_play_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='original_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/original/', verbose_name='原始视频文件'),
        ),
        migrations.AddField(
            model_name='video',
            name='processed_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/processed/', verbose_name='处理后的文件'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='缩略图'),
        ),
    ]
