# Generated by Django 5.2.1 on 2025-05-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_video_file_video_original_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos\\original', verbose_name='原始视频文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='processed_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos\\processed', verbose_name='处理后的文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos\\thumbnails', verbose_name='缩略图'),
        ),
    ]
