# Generated by Django 5.2.1 on 2025-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_original_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField(verbose_name='系列ID')),
                ('video_id', models.IntegerField(verbose_name='视频ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '重试记录',
                'verbose_name_plural': '重试记录',
            },
        ),
    ]
