# Generated by Django 5.2.1 on 2025-05-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_retryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retryrecord',
            name='series_id',
        ),
        migrations.RemoveField(
            model_name='retryrecord',
            name='video_id',
        ),
        migrations.AddField(
            model_name='retryrecord',
            name='series',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.series', verbose_name='系列'),
        ),
        migrations.AddField(
            model_name='retryrecord',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video', verbose_name='视频'),
        ),
    ]
