# Generated by Django 5.1.6 on 2025-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_quantity', models.IntegerField(default=0, verbose_name='持仓数量')),
                ('cost_price', models.IntegerField(default=0, verbose_name='持仓成本')),
                ('code', models.IntegerField(default=0, verbose_name='股票代码')),
                ('name', models.CharField(max_length=20, verbose_name='股票名称')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'holding',
            },
        ),
    ]
