# Generated by Django 5.1.6 on 2025-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
