# Generated by Django 5.1.6 on 2025-02-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0002_alter_holdingmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmodel',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='持仓成本'),
        ),
    ]
