# Generated by Django 5.1.6 on 2025-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0004_alter_holdingmodel_options_holdingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingmodel',
            name='status',
            field=models.CharField(default='持仓', max_length=10, verbose_name='状态'),
        ),
    ]
