# Generated by Django 5.1.6 on 2025-02-17 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0005_holdingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingmodel',
            name='holding_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='持仓时间'),
            preserve_default=False,
        ),
    ]
