# Generated by Django 5.1.6 on 2025-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0006_holdingmodel_holding_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmodel',
            name='holding_at',
            field=models.DateTimeField(verbose_name='持仓时间'),
        ),
    ]
