# Generated by Django 5.1.6 on 2025-02-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0007_alter_holdingmodel_holding_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录管理',
                'db_table': 'transaction_record',
            },
        ),
    ]
