# Generated by Django 5.1.6 on 2025-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0008_transactionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
