# Generated by Django 5.1.6 on 2025-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0009_remove_transactionrecord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='stock_code',
            field=models.CharField(default='000000', max_length=10, verbose_name='股票代码'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='stock_name',
            field=models.CharField(default='无', max_length=50, verbose_name='股票名称'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='交易价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_quantity',
            field=models.IntegerField(default=0, verbose_name='交易数量'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.CharField(default='买入', max_length=10, verbose_name='交易类型'),
        ),
    ]
