# Generated by Django 5.1.6 on 2025-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0010_transactionrecord_stock_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, '买入'), (2, '卖出')], default=1),
        ),
    ]
