# Generated by Django 5.1.6 on 2025-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0011_alter_transactionrecord_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='交易金额'),
        ),
    ]
