# Generated by Django 5.1.6 on 2025-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0012_alter_transactionrecord_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingmodel',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='持仓成本'),
        ),
        migrations.AlterField(
            model_name='holdingmodel',
            name='status',
            field=models.IntegerField(choices=[(1, '持仓'), (2, '空仓')], default=1),
        ),
    ]
