# Generated by Django 5.1.6 on 2025-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0013_alter_holdingmodel_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.AddField(
            model_name='holdingmodel',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前价格'),
            preserve_default=False,
        ),
    ]
