# Generated by Django 5.1.6 on 2025-03-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha_selector', '0014_alter_transactionrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingmodel',
            name='current_price',
        ),
    ]
